// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using auradocs_api.Contexts;

#nullable disable

namespace auradocs_api.Migrations
{
    [DbContext(typeof(AuradocsContext))]
    [Migration("20260314104938_RemoveParentFolderIdMarkNotNull")]
    partial class RemoveParentFolderIdMarkNotNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Document", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<bool>("boolIsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("boolIsDeleted");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtCreatedOn");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<string>("strContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strContent");

                    b.Property<string>("strGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strGuid");

                    b.Property<string>("strTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strTitle");

                    b.Property<int>("uCreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uCreatedBy");

                    b.Property<int>("uCurrentVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("uCurrentVersionId");

                    b.Property<int>("uOwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uOwnerUserId");

                    b.Property<int>("uStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("uStatusId");

                    b.HasKey("uId");

                    b.HasIndex("uCreatedBy");

                    b.HasIndex("uOwnerUserId");

                    b.HasIndex("uStatusId")
                        .HasDatabaseName("IX_Document_boolIsDeleted");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("DocumentFolder", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<DateTime>("dtCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtCreatedAt");

                    b.Property<string>("strGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strGuid");

                    b.Property<int>("uDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("uDocumentId");

                    b.Property<int>("uFolderId")
                        .HasColumnType("integer")
                        .HasColumnName("uFolderId");

                    b.HasKey("uId");

                    b.HasIndex("uDocumentId")
                        .HasDatabaseName("IX_DocumentFolder_uDocumentId");

                    b.HasIndex("uFolderId")
                        .HasDatabaseName("IX_DocumentFolder_uFolderId");

                    b.ToTable("DocumentFolder", (string)null);
                });

            modelBuilder.Entity("DocumentSharedWithUser", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<DateTime>("dtAccessGivenOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtAccessGivenOn");

                    b.Property<int>("uAccessgiven")
                        .HasColumnType("integer")
                        .HasColumnName("uAccessgiven");

                    b.Property<int>("uSharedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uSharedBy");

                    b.Property<int>("uSharedDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("uSharedDocumentId");

                    b.Property<int>("uSharedWith")
                        .HasColumnType("integer")
                        .HasColumnName("uSharedWith");

                    b.HasKey("uId");

                    b.HasIndex("uSharedBy")
                        .HasDatabaseName("IX_DocumentsSharedWithUser_uSharedBy");

                    b.HasIndex("uSharedDocumentId");

                    b.HasIndex("uSharedWith")
                        .HasDatabaseName("IX_DocumentsSharedWithUser_uSharedWith");

                    b.ToTable("DocumentsSharedWithUsers", (string)null);
                });

            modelBuilder.Entity("DocumentVersion", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<string>("strContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strContent");

                    b.Property<string>("strGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strGuid");

                    b.Property<int>("uDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("uDocumentId");

                    b.Property<int>("uUpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uUpdatedBy");

                    b.Property<int>("uVersion")
                        .HasColumnType("integer")
                        .HasColumnName("uVersion");

                    b.HasKey("uId");

                    b.HasIndex("uDocumentId")
                        .HasDatabaseName("IX_Folder_uDocumentId");

                    b.HasIndex("uUpdatedBy")
                        .HasDatabaseName("IX_Folder_uUpdatedBy");

                    b.ToTable("DocumentVersion", (string)null);
                });

            modelBuilder.Entity("DropdownOptionsGroup", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<string>("strValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("practicearea");

                    b.Property<int>("uKey")
                        .HasColumnType("integer")
                        .HasColumnName("domainId");

                    b.HasKey("uId");

                    b.HasIndex("uKey");

                    b.ToTable("domainpracticeareadropdown", (string)null);

                    b.HasData(
                        new
                        {
                            uId = 1,
                            strValue = "Web Development",
                            uKey = 1
                        },
                        new
                        {
                            uId = 2,
                            strValue = "Mobile Development",
                            uKey = 1
                        },
                        new
                        {
                            uId = 3,
                            strValue = "Cloud Engineering",
                            uKey = 1
                        },
                        new
                        {
                            uId = 4,
                            strValue = "DevOps",
                            uKey = 1
                        },
                        new
                        {
                            uId = 5,
                            strValue = "Data Engineering",
                            uKey = 1
                        },
                        new
                        {
                            uId = 6,
                            strValue = "Cybersecurity",
                            uKey = 1
                        },
                        new
                        {
                            uId = 7,
                            strValue = "AI / Machine Learning",
                            uKey = 1
                        },
                        new
                        {
                            uId = 8,
                            strValue = "QA / Testing",
                            uKey = 1
                        },
                        new
                        {
                            uId = 9,
                            strValue = "QA / Testing",
                            uKey = 1
                        },
                        new
                        {
                            uId = 10,
                            strValue = "Corporate Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 11,
                            strValue = "Criminal Defense",
                            uKey = 2
                        },
                        new
                        {
                            uId = 12,
                            strValue = "Civil Litigation",
                            uKey = 2
                        },
                        new
                        {
                            uId = 13,
                            strValue = "Family Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 14,
                            strValue = "Real Estate Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 15,
                            strValue = "Intellectual Property (IP)",
                            uKey = 2
                        },
                        new
                        {
                            uId = 16,
                            strValue = "Employment & Labor Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 17,
                            strValue = "Tax Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 18,
                            strValue = "Cardiology",
                            uKey = 3
                        },
                        new
                        {
                            uId = 19,
                            strValue = "Neurology",
                            uKey = 3
                        },
                        new
                        {
                            uId = 20,
                            strValue = "Orthopedics",
                            uKey = 3
                        },
                        new
                        {
                            uId = 21,
                            strValue = "Pediatrics",
                            uKey = 3
                        },
                        new
                        {
                            uId = 22,
                            strValue = "Oncology",
                            uKey = 3
                        },
                        new
                        {
                            uId = 23,
                            strValue = "General Medicine",
                            uKey = 3
                        },
                        new
                        {
                            uId = 24,
                            strValue = "Tax Advisory",
                            uKey = 4
                        },
                        new
                        {
                            uId = 25,
                            strValue = "Audit",
                            uKey = 4
                        },
                        new
                        {
                            uId = 26,
                            strValue = "Investment Management",
                            uKey = 4
                        },
                        new
                        {
                            uId = 27,
                            strValue = "Risk Management",
                            uKey = 4
                        },
                        new
                        {
                            uId = 28,
                            strValue = "Wealth Management",
                            uKey = 4
                        },
                        new
                        {
                            uId = 29,
                            strValue = "Recruitment",
                            uKey = 5
                        },
                        new
                        {
                            uId = 30,
                            strValue = "Learning & Development",
                            uKey = 5
                        },
                        new
                        {
                            uId = 31,
                            strValue = "Employee Relations",
                            uKey = 5
                        },
                        new
                        {
                            uId = 32,
                            strValue = "Compensation & Benefits",
                            uKey = 5
                        },
                        new
                        {
                            uId = 33,
                            strValue = "Digital Marketing",
                            uKey = 6
                        },
                        new
                        {
                            uId = 34,
                            strValue = "Content Marketing",
                            uKey = 6
                        },
                        new
                        {
                            uId = 35,
                            strValue = "Branding",
                            uKey = 6
                        },
                        new
                        {
                            uId = 36,
                            strValue = "SEO",
                            uKey = 6
                        },
                        new
                        {
                            uId = 37,
                            strValue = "Market Research",
                            uKey = 6
                        },
                        new
                        {
                            uId = 38,
                            strValue = "Business Strategy",
                            uKey = 7
                        },
                        new
                        {
                            uId = 39,
                            strValue = "Operations",
                            uKey = 7
                        },
                        new
                        {
                            uId = 40,
                            strValue = "IT Consulting",
                            uKey = 7
                        },
                        new
                        {
                            uId = 41,
                            strValue = "Supply Chain",
                            uKey = 7
                        },
                        new
                        {
                            uId = 42,
                            strValue = "Corporate Finance",
                            uKey = 7
                        });
                });

            modelBuilder.Entity("Folder", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<bool>("boolIsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("boolIsDeleted");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtCreatedOn");

                    b.Property<string>("strGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strGuid");

                    b.Property<string>("strTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strTitle");

                    b.Property<int>("uCreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uCreatedBy");

                    b.Property<int>("uOwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uOwnerUserId");

                    b.Property<int?>("uParentFolderId")
                        .HasColumnType("integer")
                        .HasColumnName("uParentFolderId");

                    b.HasKey("uId");

                    b.HasIndex("uCreatedBy");

                    b.HasIndex("uOwnerUserId")
                        .HasDatabaseName("IX_Folder_uOwnerUSerId");

                    b.HasIndex("uParentFolderId")
                        .HasDatabaseName("IX_Folder_uParentFolderId");

                    b.ToTable("Folder", (string)null);
                });

            modelBuilder.Entity("ResetPasswordToken", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<bool>("boolIsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("boolIsUsed");

                    b.Property<bool>("boolIsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("boolIsVerified");

                    b.Property<DateTime>("dtCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtCreatedAt");

                    b.Property<DateTime>("dtExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtExpiredAt");

                    b.Property<string>("strGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strGuid");

                    b.Property<string>("strToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strToken");

                    b.Property<string>("strUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strUserId");

                    b.HasKey("uId");

                    b.HasIndex("strUserId")
                        .HasDatabaseName("IX_ResetPasswordToken_strUserId");

                    b.ToTable("ResetPasswordToken", (string)null);
                });

            modelBuilder.Entity("auradocs_api.Models.DropdownOptions", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<string>("strOption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domainName");

                    b.HasKey("uId");

                    b.HasIndex("uId")
                        .IsUnique()
                        .HasDatabaseName("IX_domainname_uId");

                    b.ToTable("domainnamedropdown", (string)null);

                    b.HasData(
                        new
                        {
                            uId = 1,
                            strOption = "IT"
                        },
                        new
                        {
                            uId = 2,
                            strOption = "Legal"
                        },
                        new
                        {
                            uId = 3,
                            strOption = "Healthcare"
                        },
                        new
                        {
                            uId = 4,
                            strOption = "Finance"
                        },
                        new
                        {
                            uId = 5,
                            strOption = "HR"
                        },
                        new
                        {
                            uId = 6,
                            strOption = "Marketing"
                        },
                        new
                        {
                            uId = 7,
                            strOption = "Consulting"
                        });
                });

            modelBuilder.Entity("auradocs_api.Models.User", b =>
                {
                    b.Property<int>("uUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uUid"));

                    b.Property<bool>("boolIsUserActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsUserActivated");

                    b.Property<DateTime>("dtAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtAdded");

                    b.Property<DateTime?>("dtLastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtLastLogin");

                    b.Property<string>("strAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AccountType");

                    b.Property<string>("strAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Address");

                    b.Property<string>("strDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Description");

                    b.Property<string>("strFullName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("FullName");

                    b.Property<string>("strGuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Guid");

                    b.Property<string>("strJobTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("strJobTitle");

                    b.Property<string>("strOrganizationName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("strOrganizationName");

                    b.Property<string>("strPassword")
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("strPasswordSalt")
                        .HasColumnType("text")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("strProfilePictureURL")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePictureUrl");

                    b.Property<string>("strUserId")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("Email");

                    b.Property<int>("strUserRole")
                        .HasColumnType("integer")
                        .HasColumnName("UserRole");

                    b.Property<string>("strphoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("uDomainType")
                        .HasColumnType("integer")
                        .HasColumnName("DomainType");

                    b.Property<int>("uPracticeArea")
                        .HasColumnType("integer")
                        .HasColumnName("PracticeArea");

                    b.HasKey("uUid");

                    b.HasIndex("strUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("strphoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_PhoneNumber");

                    b.HasIndex("uDomainType");

                    b.HasIndex("uPracticeArea");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Document", b =>
                {
                    b.HasOne("auradocs_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uCreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Folder_uCreatedBy");

                    b.HasOne("auradocs_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uOwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Folder_uOwnerUserId");
                });

            modelBuilder.Entity("DocumentFolder", b =>
                {
                    b.HasOne("Document", null)
                        .WithMany()
                        .HasForeignKey("uDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentFolder_uDocumentId");

                    b.HasOne("Folder", null)
                        .WithMany()
                        .HasForeignKey("uFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentFolder_uFolderId");
                });

            modelBuilder.Entity("DocumentSharedWithUser", b =>
                {
                    b.HasOne("auradocs_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uSharedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentsSharedWithUser_uSharedBy");

                    b.HasOne("Document", null)
                        .WithMany()
                        .HasForeignKey("uSharedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentsSharedWithUser_uSharedDocumentId");

                    b.HasOne("auradocs_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uSharedWith")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentsSharedWithUser_uSharedWith");
                });

            modelBuilder.Entity("DocumentVersion", b =>
                {
                    b.HasOne("Document", null)
                        .WithMany()
                        .HasForeignKey("uDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentVersion_uDocumentId");

                    b.HasOne("auradocs_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uUpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentVersion_uUpdatedBy");
                });

            modelBuilder.Entity("DropdownOptionsGroup", b =>
                {
                    b.HasOne("DropdownOptionsGroup", null)
                        .WithMany()
                        .HasForeignKey("uKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Dropdownoptionsgroup_ukey");
                });

            modelBuilder.Entity("Folder", b =>
                {
                    b.HasOne("auradocs_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uCreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Folder_uCreatedBy");

                    b.HasOne("auradocs_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uOwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Folder_uOwnerUserId");
                });

            modelBuilder.Entity("auradocs_api.Models.User", b =>
                {
                    b.HasOne("auradocs_api.Models.DropdownOptions", null)
                        .WithMany()
                        .HasForeignKey("uDomainType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_uDomainType");

                    b.HasOne("DropdownOptionsGroup", null)
                        .WithMany()
                        .HasForeignKey("uPracticeArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_uPracticeArea");
                });
#pragma warning restore 612, 618
        }
    }
}
