// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using auradocs_api.Contexts;

#nullable disable

namespace auradocs_api.Migrations
{
    [DbContext(typeof(AuradocsContext))]
    [Migration("20260212192028_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DropdownOptionsGroup", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<string>("strValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("practicearea");

                    b.Property<int>("uKey")
                        .HasColumnType("integer")
                        .HasColumnName("domainId");

                    b.HasKey("uId");

                    b.HasIndex("uKey");

                    b.ToTable("domainpracticeareadropdown", (string)null);

                    b.HasData(
                        new
                        {
                            uId = 1,
                            strValue = "Web Development",
                            uKey = 1
                        },
                        new
                        {
                            uId = 2,
                            strValue = "Mobile Development",
                            uKey = 1
                        },
                        new
                        {
                            uId = 3,
                            strValue = "Cloud Engineering",
                            uKey = 1
                        },
                        new
                        {
                            uId = 4,
                            strValue = "DevOps",
                            uKey = 1
                        },
                        new
                        {
                            uId = 5,
                            strValue = "Data Engineering",
                            uKey = 1
                        },
                        new
                        {
                            uId = 6,
                            strValue = "Cybersecurity",
                            uKey = 1
                        },
                        new
                        {
                            uId = 7,
                            strValue = "AI / Machine Learning",
                            uKey = 1
                        },
                        new
                        {
                            uId = 8,
                            strValue = "QA / Testing",
                            uKey = 1
                        },
                        new
                        {
                            uId = 9,
                            strValue = "QA / Testing",
                            uKey = 1
                        },
                        new
                        {
                            uId = 10,
                            strValue = "Corporate Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 11,
                            strValue = "Criminal Defense",
                            uKey = 2
                        },
                        new
                        {
                            uId = 12,
                            strValue = "Civil Litigation",
                            uKey = 2
                        },
                        new
                        {
                            uId = 13,
                            strValue = "Family Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 14,
                            strValue = "Real Estate Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 15,
                            strValue = "Intellectual Property (IP)",
                            uKey = 2
                        },
                        new
                        {
                            uId = 16,
                            strValue = "Employment & Labor Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 17,
                            strValue = "Tax Law",
                            uKey = 2
                        },
                        new
                        {
                            uId = 18,
                            strValue = "Cardiology",
                            uKey = 3
                        },
                        new
                        {
                            uId = 19,
                            strValue = "Neurology",
                            uKey = 3
                        },
                        new
                        {
                            uId = 20,
                            strValue = "Orthopedics",
                            uKey = 3
                        },
                        new
                        {
                            uId = 21,
                            strValue = "Pediatrics",
                            uKey = 3
                        },
                        new
                        {
                            uId = 22,
                            strValue = "Oncology",
                            uKey = 3
                        },
                        new
                        {
                            uId = 23,
                            strValue = "General Medicine",
                            uKey = 3
                        },
                        new
                        {
                            uId = 24,
                            strValue = "Tax Advisory",
                            uKey = 4
                        },
                        new
                        {
                            uId = 25,
                            strValue = "Audit",
                            uKey = 4
                        },
                        new
                        {
                            uId = 26,
                            strValue = "Investment Management",
                            uKey = 4
                        },
                        new
                        {
                            uId = 27,
                            strValue = "Risk Management",
                            uKey = 4
                        },
                        new
                        {
                            uId = 28,
                            strValue = "Wealth Management",
                            uKey = 4
                        },
                        new
                        {
                            uId = 29,
                            strValue = "Recruitment",
                            uKey = 5
                        },
                        new
                        {
                            uId = 30,
                            strValue = "Learning & Development",
                            uKey = 5
                        },
                        new
                        {
                            uId = 31,
                            strValue = "Employee Relations",
                            uKey = 5
                        },
                        new
                        {
                            uId = 32,
                            strValue = "Compensation & Benefits",
                            uKey = 5
                        },
                        new
                        {
                            uId = 33,
                            strValue = "Digital Marketing",
                            uKey = 6
                        },
                        new
                        {
                            uId = 34,
                            strValue = "Content Marketing",
                            uKey = 6
                        },
                        new
                        {
                            uId = 35,
                            strValue = "Branding",
                            uKey = 6
                        },
                        new
                        {
                            uId = 36,
                            strValue = "SEO",
                            uKey = 6
                        },
                        new
                        {
                            uId = 37,
                            strValue = "Market Research",
                            uKey = 6
                        },
                        new
                        {
                            uId = 38,
                            strValue = "Business Strategy",
                            uKey = 7
                        },
                        new
                        {
                            uId = 39,
                            strValue = "Operations",
                            uKey = 7
                        },
                        new
                        {
                            uId = 40,
                            strValue = "IT Consulting",
                            uKey = 7
                        },
                        new
                        {
                            uId = 41,
                            strValue = "Supply Chain",
                            uKey = 7
                        },
                        new
                        {
                            uId = 42,
                            strValue = "Corporate Finance",
                            uKey = 7
                        });
                });

            modelBuilder.Entity("auradocs_api.Models.DropdownOptions", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uId"));

                    b.Property<string>("strOption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domainName");

                    b.HasKey("uId");

                    b.HasIndex("uId")
                        .IsUnique()
                        .HasDatabaseName("IX_domainname_uId");

                    b.ToTable("domainnamedropdown", (string)null);

                    b.HasData(
                        new
                        {
                            uId = 1,
                            strOption = "IT"
                        },
                        new
                        {
                            uId = 2,
                            strOption = "Legal"
                        },
                        new
                        {
                            uId = 3,
                            strOption = "Healthcare"
                        },
                        new
                        {
                            uId = 4,
                            strOption = "Finance"
                        },
                        new
                        {
                            uId = 5,
                            strOption = "HR"
                        },
                        new
                        {
                            uId = 6,
                            strOption = "Marketing"
                        },
                        new
                        {
                            uId = 7,
                            strOption = "Consulting"
                        });
                });

            modelBuilder.Entity("auradocs_api.Models.IndividualUser", b =>
                {
                    b.Property<int>("uUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uUid"));

                    b.Property<bool>("boolIsUserActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsUserActivated");

                    b.Property<DateTime>("dtAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtAdded");

                    b.Property<DateTime>("dtLastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtLastLogin");

                    b.Property<string>("strAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Address");

                    b.Property<string>("strDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Description");

                    b.Property<string>("strEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("Email");

                    b.Property<string>("strFullName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("FullName");

                    b.Property<Guid>("strGuid")
                        .HasMaxLength(100)
                        .HasColumnType("uuid")
                        .HasColumnName("Guid");

                    b.Property<string>("strPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("strPasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("strProfilePictureURL")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePictureUrl");

                    b.Property<int>("strUserRole")
                        .HasColumnType("integer")
                        .HasColumnName("UserRole");

                    b.Property<string>("strphoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("uAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AccountType");

                    b.Property<string>("uDomainType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DomainType");

                    b.Property<string>("uPracticeArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PracticeArea");

                    b.HasKey("uUid");

                    b.HasIndex("strEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_IndividualUser_Email");

                    b.HasIndex("strphoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_IndividualUser_PhoneNumber");

                    b.ToTable("IndividualUsers", (string)null);
                });

            modelBuilder.Entity("auradocs_api.Models.OrganizationUser", b =>
                {
                    b.Property<int>("uUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uUid"));

                    b.Property<bool>("boolIsUserActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsUserActivated");

                    b.Property<DateTime>("dtAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtAdded");

                    b.Property<DateTime>("dtLastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtLastLogin");

                    b.Property<string>("strAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Address");

                    b.Property<string>("strDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Description");

                    b.Property<string>("strFullName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("FullName");

                    b.Property<Guid>("strGuid")
                        .HasMaxLength(100)
                        .HasColumnType("uuid")
                        .HasColumnName("Guid");

                    b.Property<string>("strJobTitle")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("jobTitle");

                    b.Property<string>("strOrganizationId")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("Email");

                    b.Property<string>("strOrganizationName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Organization");

                    b.Property<string>("strPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("strPasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("strProfilePictureURL")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePictureUrl");

                    b.Property<int>("strUserRole")
                        .HasColumnType("integer")
                        .HasColumnName("UserRole");

                    b.Property<string>("strphoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("uAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AccountType");

                    b.Property<string>("uDomainType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DomainType");

                    b.Property<string>("uPracticeArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PracticeArea");

                    b.HasKey("uUid");

                    b.HasIndex("strOrganizationId")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUser_OrganizationId");

                    b.HasIndex("strphoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganizationUser_PhoneNumber");

                    b.ToTable("OrganizationUsers", (string)null);
                });

            modelBuilder.Entity("DropdownOptionsGroup", b =>
                {
                    b.HasOne("DropdownOptionsGroup", null)
                        .WithMany()
                        .HasForeignKey("uKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Dropdownoptionsgroup_ukey");
                });
#pragma warning restore 612, 618
        }
    }
}
